# Generated by Django 2.2.4 on 2019-08-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='PollUser',
        ),
    ]
